# Generated by Django 4.2.4 on 2023-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Desayunos', 'Desayunos'), ('Almuerzos', 'Almuerzos'), ('Bebidas', 'Bebidas'), ('Unico', 'Unico')], default='Seleccione', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, max_length=4),
            preserve_default=False,
        ),
    ]
